# Generated by Django 6.0.3 on 2026-04-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('word', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('weak', 'weak'), ('known', 'known')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='WordSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField()),
                ('example', models.TextField()),
                ('part_of_speech', models.CharField(blank=True, default='', max_length=50)),
                ('synonyms', models.JSONField(blank=True, default=list)),
                ('antonyms', models.JSONField(blank=True, default=list)),
                ('usage', models.TextField(blank=True, default='')),
                ('examples', models.JSONField(blank=True, default=list)),
                ('register', models.CharField(blank=True, choices=[('formal', 'Formal'), ('informal', 'Informal'), ('slang', 'Slang')], default='', max_length=20)),
                ('connotation', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='', max_length=20)),
                ('collocations', models.JSONField(blank=True, default=list)),
                ('word_forms', models.JSONField(blank=True, default=dict)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.lexeme')),
            ],
        ),
    ]
