# Generated by Django 6.0.3 on 2026-03-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_paragraph_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paragraph',
            old_name='name',
            new_name='title',
        ),
    ]
