# Generated by Django 6.0.3 on 2026-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_rename_name_paragraph_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
