# Generated by Django 6.0.3 on 2026-04-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_paragraph_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='antonyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='word',
            name='collocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='word',
            name='connotation',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='register',
            field=models.CharField(blank=True, choices=[('formal', 'Formal'), ('informal', 'Informal'), ('slang', 'Slang')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='word',
            name='usage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='word',
            name='word_forms',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
