# Generated by Django 6.0.3 on 2026-04-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_quiz_question_lexeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quiz.question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='state',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
